### ISSUE TITLE
[FEAT] - Endpoint with list of sources

### ISSUE THREAD

**Issue by MizouziE** [Energy-Price-News-API/energy-prices-api#118]
### What feature would you like to see?

A new endpoint added that lists:
- The names of available sources
- Links to the single source endpoint for each
- Maybe an image for the source

### Possible implementation

something like `/api/news/sources` would be good.

### Additional information

It must be dynamic and generated from the `src/data/sources.json` file.

Bear in mind that the single source endpoint for each is derived from the name inside the `src/controller/api/newsAPIController.js` and the line of code looks something like:
```js
(source) => source.name.toLowerCase().replace(/ /g, '') == sourceId
```

**Comment by MuminAhmadKhan** [comment]
Hello @MizouziE , I'd like to work on this issue.

**Comment by MizouziE** [comment]
> Hello @MizouziE , I'd like to work on this issue.

Fantastic! Thanks a lot and please ask any questions if you need to, I'll answer as soon as I possibly can.

**Comment by MuminAhmadKhan** [comment]
Lets say the source is sky news  then the single source endpoint is  .../api/news/skynews [https://energy-price-news-api.herokuapp.com/api/news/skynews] , right?

**Comment by MizouziE** [comment]
> Lets say the source is sky news  then the single source endpoint is  .../api/news/skynews [https://energy-price-news-api.herokuapp.com/api/news/skynews] , right?

Yes, exactly that. It's the name, without spaces and all lowercase.

**Comment by MuminAhmadKhan** [comment]
Should We include image url into sources.json as they rarely change or should I use cheerio.io which would result in more resource and time consumption for users?

**Comment by MizouziE** [comment]
> Should We include image url into sources.json as they rarely change or should I use cheerio.io which would result in more resource and time consumption for users?

That is a good point! I would say, get it working with cheerio for now but create an issue to change the structure over later. The images are already a separate issue as I'd prefer that the image for the articles object returned were specific to each article rather than just the og:image of the news site. This og:image is actually what would be best suited to what you're building here.
