### ISSUE TITLE
[BUG]: Server crashes due to twitter searchs

### ISSUE THREAD

**Issue by TAKANOME-DEV** [Energy-Price-News-API/energy-prices-api#119]
### What bug did you encounter?

After installing the dependencies and start the server, it crashes. After looking through the console, I found that there are some issues with the twitter search. 
I wonder why add the `keywords` on the search query, I think that caused the issue :
```js
 await axios.get(
      'https://twitter.com/search?p=from%3A' +
        twitterAccount.account +
        `${keyword}`
    );
```
The simplified error is here: 
```sh
  address: '104.244.42.1',
  port: 443,
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.26.1'
    },
    method: 'get',
    url: 'https://twitter.com/search?p=from%3ABarackObamapetrol prices',
    data: undefined
  },
  request: <ref *4> Writable {
      protocol: 'https:',
      path: '/search?p=from%3ABarackObamapetrol%20prices',
      method: 'GET',
      headers: {
        Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.26.1'
      },
      agent: undefined,
      agents: { http: undefined, https: undefined },
      auth: undefined,
      # -----------------------------------------------------------------------------
      hostname: 'twitter.com',
      port: null,
      pathname: '/search',
      search: '?p=from%3ABarackObamapetrol%20prices'
      # -----------------------------------------------------------------------------
    },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

### What did you expect to happen?

I was expecting the server to start and render the homepage after visiting `http://localhost:8000/`

**Comment by MizouziE** [comment]
Shall we open a new branch to start migrating the twitter searching over to simple calls to the Twitter API?

I was reading [the docs](https://developer.twitter.com/en/docs/twitter-api) and it looks like a much better alternative but does require a bit of work to set up. It would certainly take a load off our server by just forwarding queries, so it's worth it.

Let me know what you think.

**Comment by TAKANOME-DEV** [comment]
Oh the issue was the space in the keyword, I replaced all `spaces` with `%20` and it did work. So I'm thinking about adding a new utility function that will filter and replace spaces with `%20`.

And yeah migrating to twitter API sounds good to me. please go ahead :pray:

**Comment by MizouziE** [comment]
THE SPACES!!! That never even occurred to me. Nice catch!

The,
> :warning: It works but if you click to that twitter link, you will see no results :no_mouth:

problem is on the twitter end, I think some results will show on a page refresh... I think. I noticed something like this a long time ago and just stepped away and forgot about it, bu tit had some weird workaround like that.

Definitely go for the util func though as I don't see the API migration happening quickly!
