### ISSUE TITLE
Add region attribute  to existing news sources and update regions.json

### ISSUE THREAD

**Issue by MuminAhmadKhan** [Energy-Price-News-API/energy-prices-api#124]
### What would you like to share?

Existing new sources in data/sources.json have empty region attribute , add the corresponding region to each source 
like Americas , Europe , Asia .
Also if a source is in a region that is not already present in data/regions.json , add the new region to it as well .

**Comment by Dev79844** [comment]
I would like to work on this.

**Comment by MizouziE** [comment]
Thanks @Dev79844 , please go ahead
