### ISSUE TITLE
[CHORE] - Update Endpoints on homepage

### ISSUE THREAD

**Issue by MizouziE** [Energy-Price-News-API/energy-prices-api#126]
### What work needs to be performed?

On the homepage for the site is a list of possible endpoints with a clickable link so people may navigate ti them directly.

Recently we've added a number of endpoints:
- `/news/sources`
- `/news/regions`
- `/news/regions/{regionId}`

Please add each with a brief description like the ones already there.

## Also
Please comment out the twitter endpoint for the time being as it is not working correctly and will be address separately.

### Additional information

The part to edit is in `src/views/index.html` somewhere after/around line 80.

The list will show up here:
![image](https://user-images.githubusercontent.com/90829439/189547315-c9484fb2-4b21-4f2d-ad4e-fefab72c1a7f.png)

**Comment by susi189** [comment]
Hey @MizouziE, I would like to work on that one

**Comment by MizouziE** [comment]
Hey @susi189 that would be great! Assigning you now, it's all yours. Thanks!

**Comment by MizouziE** [comment]
Hi @susi189 , do you have a PR ready for this? I try to keep it as fair as possible on here and check after one week if I can open an un-closed issue up to be assigned to someone else.

**Comment by susi189** [comment]
@MizouziE sorry, feel free to re-assign

**Comment by MizouziE** [comment]
@susi189 no need to be sorry at all! Please do keep an eye on the project and I hope we have a suitable opportunity soon :pray: 

You'll always have first dibbs on this one if you submit an approved PR before anyone else.
