### ISSUE TITLE
[FEAT] - Pagination of articles

### ISSUE THREAD

**Issue by MizouziE** [Energy-Price-News-API/energy-prices-api#127]
### What feature would you like to see?

The list of returned articles is getting quite long. It might be time to start thinking about adding pagination to the list.

### Possible implementation

Set up as an accepted query parameter with a default setting of **unpaginated** if not specified to prevent breaking apps already made to consume the data as it is.

We'll need the usual things like:
- `url` for next & previous pages
- current page number
- total item count
- total page count
- items per page

**Comment by MizouziE** [comment]
@MuminAhmadKhan absolutely! 

I had a look at some packages like [pagination](https://www.npmjs.com/package/pagination) and [pagination-object](https://www.npmjs.com/package/pagination-object) which I wouldn't be against implementing OR I'd be more than happy if you wanted to build it from scratch. 

Take a look at the packages anyway as they'd make a good guideline at the very least.

Thanks!

**Comment by TAKANOME-DEV** [comment]
As @MizouziE said, I would suggest that you build it from scratch instead of using a library or a pagination library.
I think it's more simple to use [lodash slice method](https://lodash.com/docs/4.17.15#slice)

**Comment by MuminAhmadKhan** [comment]
Thanks @MizouziE  and @TAKANOME-DEV , I will look into the suggestions and update you guys accordingly!

**Comment by MuminAhmadKhan** [comment]
For this url :http://localhost:8000/api/news/?page=2&limit=6
![image](https://user-images.githubusercontent.com/63766734/190893786-dfbbf1c7-2e4a-4934-9df8-257b77eb1a54.png)
For this url :http://localhost:8000/api/news/?page=2
![image](https://user-images.githubusercontent.com/63766734/190893796-b7aab32b-9814-425b-9a38-20933fbb498d.png)
Limit is 5 by default.
For this url :For this url :http://localhost:8000/api/news/
![image](https://user-images.githubusercontent.com/63766734/190893859-6322e970-9c39-426a-807a-6cebecd35c1b.png)
By default no pagination.
Is this  what was expected ?

**Comment by MizouziE** [comment]
Yes that's absolutely perfect. You built that already??

**Comment by MuminAhmadKhan** [comment]
Yes I have built it
