### ISSUE TITLE
OTHER - add `.github` repo for health files

### ISSUE THREAD

**Issue by TAKANOME-DEV** [Energy-Price-News-API/energy-prices-api#131]
### What would you like to share?

Adding a community health files for [@Energy-Price-NewsAPI](https://github.com/Energy-Price-News-API) organization.

This repo will hold the health files like `CONTRIBUTING.md` `CODE_OF_CONDUCT` `ISSUE_TEMPLATE` etc and GitHub will use it and display default files for any repository owned by @Energy-Price-NewsAPI](https://github.com/Energy-Price-News-API)  that does not have its own file of that type in any of the following places: 
- the root of the repository
- the .github folder
- the docs folder

Learn more about this [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)
An example can be found [here](https://github.com/open-sauced/.github/tree/main/.github)

@MizouziE this one is for you :sunglasses:

**Comment by MizouziE** [comment]
Finally done  :sweat_smile:
