### ISSUE TITLE
[CHORE] - Clear out a missed `console.log()` 

### ISSUE THREAD

**Issue by MizouziE** [Energy-Price-News-API/energy-prices-api#132]
### What work needs to be performed?

We recently had a very cool pagination feature added but the reviewer (... me) missed that one `console.log()` was left in from development.

It all works perfectly, but we need to remove one line to stop it dumping to the console every time the pagination is initiated.

Look in: `./src/utils/paginate.js`

And remove: `console.log(results)` from line 36.

That's all.

**Comment by TeaBizzy** [comment]
Hi @MizouziE I would like to contribute to this project and handle this issue.

**Comment by TAKANOME-DEV** [comment]
@TeaBizzy thanks for your interest in contributing.
You can start working on it if you wish, @MizouziE will assign it to you ASAP :rocket:

**Comment by MizouziE** [comment]
Sorry I'm late, thanks a lot @TeaBizzy !

**Comment by TeaBizzy** [comment]
@MizouziE Friendly reminder we can close this now :smiley:
