### ISSUE TITLE
[BUG] keyword.replaceAll is not a function.

### ISSUE THREAD

**Issue by TeaBizzy** [Energy-Price-News-API/energy-prices-api#138]
### What bug did you encounter?

When running npm run dev the above error is shown multiple time and the terminal hangs.

Steps to reproduce.

1. Clone the repo into a new folder.
2. Navigate to the fold in terminal.
3. type `npm install`
4. type `npm run dev`

### What did you expect to happen?

In regards to discussion #137, I'm assuming this is suppose to build the site and host it on port 8000 to view on the local machine.

(Please correct me if I'm wrong)

### Screenshots

![Screenshot from 2022-09-22 10-03-16](https://user-images.githubusercontent.com/111951212/191829104-9b706f4f-a870-44c1-84a4-95cff146d6e0.png)
![Screenshot from 2022-09-22 10-03-43](https://user-images.githubusercontent.com/111951212/191829120-05c0bedf-a46f-44d9-9dcb-da78011595b7.png)

Opening index.html manually results in the following:

![Screenshot from 2022-09-22 10-10-12](https://user-images.githubusercontent.com/111951212/191829194-d4f58ff7-f4be-442b-bae7-4e0841801617.png)

### Additional information

Not sure if this is a problem with newly cloned repos, or if others are now having this issue. I believe I know how to fix the issue as I recently had the same issue with `replaceAll` in the past.

I would be willing to try and fix it if you could please assign it to me I will attempt it in the next 24hrs.

**Comment by MizouziE** [comment]
I have tried to give as detailed an answer as possible to this in #137 and  will close this issue due to the server the site being run on using Node v16.x.x and this problem does not occur there.
