### ISSUE TITLE
[BUG] Links in index.html are broken

### ISSUE THREAD

**Issue by TeaBizzy** [Energy-Price-News-API/energy-prices-api#139]
### What bug did you encounter?

When opening `index.html` in a browser, the CSS isn't working and the logo is broken.

### What did you expect to happen?

Webpage should be stylized by using `./public/css/styles.css` and look identical to [This link on the repo](https://energy-price-news-api.herokuapp.com/).

### Screenshots

Currently opening `index.html` looks like this:
![Screenshot from 2022-09-22 10-10-12](https://user-images.githubusercontent.com/111951212/191835833-c34aa82b-f40e-44ca-a963-e20e987d3e35.png)

It should look like this:
![Screenshot from 2022-09-22 15-38-40](https://user-images.githubusercontent.com/111951212/191836097-a5d737a1-7203-422c-8750-ab4f29859053.png)

### Additional information

To fix we just need to re-link `styles.css` and the logo image.

I would be willing to fix if you could assign it to me :smiley: 

Thank you,

**Comment by TAKANOME-DEV** [comment]
Oh nice catch @TeaBizzy:clap: 
Feel free to open a PR on this, @MizouziE will go through it as soon as possible.

**Comment by MizouziE** [comment]
Please refer to #137 
I'll close this for the time being.
