### ISSUE TITLE
Links to endpoints

### ISSUE THREAD

**Issue by MizouziE** [Energy-Price-News-API/energy-prices-api#14]
Let's include some clickable links to the current endpoints on the homepage `app.get('/', (req, res) {...})`. 

Also;
- short explanations
- link to this repo
- project aims

Under here;
![image](https://user-images.githubusercontent.com/90829439/166745312-7dd76637-c39c-4225-a466-316037089966.png)

**Comment by Yoshemith** [comment]
Hi @MizouziE I was looking through the project and I really liked the idea you're working on, so I was thinking if I could start contributing to this issue, If there's no one working on this currently, of course, I'd love to.

**Comment by MizouziE** [comment]
Thank you very much @Yoshemith ! That means a lot and your input would be really appreciated. 

Nobody is working in it currently, I don't have any set goals aside from the suggestions I put in the issue but my opinion is that whoever is working on it should feel free to execute however they see fit. I'm always here to discuss if need be. Really looking forward to working together!

**Comment by hendurhance** [comment]
This is a very good idea. I'd love to work on this issue.

**Comment by MizouziE** [comment]
Hi @hendurhance, thanks! At the moment it's being worked on, but once @Yoshemith is happy with what they've got done and made a PR, then I'd be very grateful for your input on further enhancements because there'll always be more to do. If you don't receive any notifications in the next week, check back with us and we'll see where we're at with it.
