### ISSUE TITLE
Test: Add a test suite for `api/news`

### ISSUE THREAD

**Issue by TAKANOME-DEV** [Energy-Price-News-API/energy-prices-api#149]
### What would you like to share?

Add a test suite for the `news` endpoints.
### Steps:
- Add a new `describe block` for `/api/news/sources` inside `/__tests__/integration-tests/routes/news.test.js`
- move the first test suite inside `news.test.js` to that describe block: `it('should return all the articles', async () => {})`
- Add test suite for all possible scenarios

### Additional information

> **Note**
> All `axios` requests are mock inside the `__mocks__` folder
> Fell free to add more mock data inside that file

**Comment by sanyamgandhak** [comment]
Hi there ,
Please assign it to me

**Comment by sanyamgandhak** [comment]
Please have a look at PR
