### ISSUE TITLE
Test: Add a test suite for `api/news/regions:regionId`

### ISSUE THREAD

**Issue by TAKANOME-DEV** [Energy-Price-News-API/energy-prices-api#152]
### What would you like to share?

Add a test suite for the `/:regionId` endpoint.
### Steps:
- Add a new `describe block` for `/api/news/sources` inside `/__tests__/integration-tests/routes/news.test.js`
- Add test suite for all possible scenarios

### Additional information

> **Note**
> All `axios` requests are mock inside the `__mocks__` folder
> Fell free to add more mock data inside that file

**Comment by reny-pacheco** [comment]
Hi there, I'm interested in this issue. Please assign this to me.
