### ISSUE TITLE
Test: Add a test suite for `api/news/sources/:sourceId`

### ISSUE THREAD

**Issue by TAKANOME-DEV** [Energy-Price-News-API/energy-prices-api#153]
### What would you like to share?

Add a test suite for the `/sourceId` endpoint.
### Steps:
- Add a new `describe block` for `/api/news/sources` inside `/__tests__/integration-tests/routes/news.test.js`
- Add test suite for all possible scenarios

### Additional information

> **Note**
> All `axios` requests are mock inside the `__mocks__` folder
> Fell free to add more mock data inside that file

**Comment by leonlafa** [comment]
It appears that this issue has been resolved.
<img width="177" alt="energy-price-news-issue-153" src="https://user-images.githubusercontent.com/44982724/194072295-4e4a9258-9e29-481c-a2d9-b13f6a0fc671.png">

**Comment by blazenn2** [comment]
@TAKANOME-DEV  @MizouziE 

Please take a look at my pull request and let me know if you are looking for more.

Thanks!
