### ISSUE TITLE
FEAT - update single source endpoint

### ISSUE THREAD

**Issue by TAKANOME-DEV** [Energy-Price-News-API/energy-prices-api#168]
### What feature would you like to see?

I think it make more sense to update the single source endpoint from `/:sourceId` to `/sources/:sourceId` like the `regions` endpoint.

### Possible implementation

- change the endpoint for the single source id in `src/routes/api/news` 
- convert the `sourceId` comming from the request params to Lowercase and remove any spaces in `src/middlewares/existingSourceMiddleware

**Comment by chinmaykumbhare** [comment]
hi @TAKANOME-DEV , can you please assign this issue to me?

**Comment by TAKANOME-DEV** [comment]
It's yours :rocket:
