### ISSUE TITLE
[CHORE] - Force Node version

### ISSUE THREAD

**Issue by MizouziE** [Energy-Price-News-API/energy-prices-api#169]
### What work needs to be performed?

We can force the version of Nodejs to use, have a look [here](https://github.com/blimmer/enforced-package-json-engines)

### Additional information

After adding the needed file, ensure that format of Node version is compatible in `package.json`

**Comment by sanyamgandhak** [comment]
Hi there ,
Please assign it to me

**Comment by sanyamgandhak** [comment]
Completed it and raised PR request . Do check

**Comment by MizouziE** [comment]
To close this issue please do the following.

1. Make a fresh fork of this repo so that you are in-line with the project
2. add a new file `.npmrc` in the root directory
3. add the line `engine-strict = true` to this new file
4. commit **only this new file**
5. open a PR to this repo

No further changes are required. My mention of the `package.json` format was just to check it still works as it is, and as you can see in the below screenshot, it still works as expected when trying to run `npm install` on Node v12:

![image](https://user-images.githubusercontent.com/90829439/193428144-e9dd1d21-f33f-49a0-9745-0b534197476e.png)

**Comment by sanyamgandhak** [comment]
> To close this issue please do the following.
> 
> 1. Make a fresh fork of this repo so that you are in-line with the project
> 2. add a new file `.npmrc` in the root directory
> 3. add the line `engine-strict = true` to this new file
> 4. commit **only this new file**
> 5. open a PR to this repo
> 
> No further changes are required. My mention of the `package.json` format was just to check it still works as it is, and as you can see in the below screenshot, it still works as expected when trying to run `npm install` on Node v12:
> 
> ![image](https://user-images.githubusercontent.com/90829439/193428144-e9dd1d21-f33f-49a0-9745-0b534197476e.png)

Hi there ,
Created new PR . Please check
