### ISSUE TITLE
Feature: add github action to welcome first-time contributor

### ISSUE THREAD

**Issue by TAKANOME-DEV** [Energy-Price-News-API/energy-prices-api#181]
### What feature would you like to see?

Add an action to welcome first-time contributor instead of us doing it every time. 
The message can be personalized as we wish.

### Possible implementation

See: 
- https://github.com/actions/first-interaction
- https://github.com/actions/github-script#welcome-a-first-time-contributor

Here is an example: https://github.com/EddieHubCommunity/LinkFree/issues/1601#issuecomment-1214289117
Here is an interesting one: https://github.com/open-sauced/open-sauced/blob/main/.github/workflows/compliance.yml

**Comment by MizouziE** [comment]
I like the way you think! I'll get on it ASAP
