### ISSUE TITLE
Bug: Source list endpoint giving incorrect URLs

### ISSUE THREAD

**Issue by MizouziE** [Energy-Price-News-API/energy-prices-api#183]
### What bug did you encounter?

Going to `/api/news/sources` gave the list of possible sources as expected, **BUT** upon following the URLs provided I got the 404 page.

### What did you expect to happen?

To be redirected to the list of articles for the desired single source

### Screenshots

We've all seen a 404

### Additional information

I believe the answer is to alter the object returned by the `getSources` method in `src/controller/api/newsAPIController.js`

It seems to be missing the additional `/sources/` before the `/:sourceId` and you could add it in here.

**Comment by chankruze** [comment]
Assign this issue to me.

**Comment by sanyamgandhak** [comment]
Hi there ,
Please assign it to me

**Comment by MizouziE** [comment]
Thanks for taking an interest @chankruze.  Ask any questions you may have if you cannot find what you need in the documentation.

**Comment by chankruze** [comment]
Sure sir 👍

**Comment by MizouziE** [comment]
@sanyamgandhak As someone else has asked before you it's only fair that they have a chance. Please feel free to offer any suggestions you have here in the issue comments cos we're all here to help one another grow.

**Comment by sanyamgandhak** [comment]
> 

Yeah !! No issued

**Comment by chankruze** [comment]
@MizouziE This issue is also with the sources by region endpoint i.e. `http://localhost:8000/api/news/regions/europe`.
