### ISSUE TITLE
Feature: Add redirect to homepage from 404 page

### ISSUE THREAD

**Issue by reny-pacheco** [Energy-Price-News-API/energy-prices-api#185]
### What feature would you like to see?

I suggest to have a **link** from 404 page to redirect the user back to homepage.

Benefits:
- The user has a clickable link to homepage instead of typing the url. (or clicking the previous button in the browser)
- The user will redirected to homepage for more information about the api.

### Possible implementation

I also suggest to center the content.

Screenshot:

![image](https://user-images.githubusercontent.com/64537418/194710812-2d1fa65e-ae62-4ecf-9fcf-c8ef846cddba.png)

**Comment by reny-pacheco** [comment]
Hi there, if this feature is accepted, I would like to work on this.

**Comment by TAKANOME-DEV** [comment]
That's a good idea :bulb: 
I would suggest to use a button that redirect back to homepage instead of a link

**Comment by reny-pacheco** [comment]
Good suggestion, maybe `a` tag with styles like a button?

**Comment by TAKANOME-DEV** [comment]
Yeah you can do that
