### ISSUE TITLE
Chore: Remove an unwanted directory

### ISSUE THREAD

**Issue by MizouziE** [Energy-Price-News-API/energy-prices-api#189]
### What work needs to be performed?

Please remove the directory `./.vscode` along with all it's contents.

After removing, please `git add .vscode` and then `git commit -m "<suitable commit message>"` and then push your changes to create a new PR.

As the folder is already included in `.gitignore` you will not need to do anything here.

### Additional information

The easiest way to do this would be via command line in the root directory:
```bash
rm -r .vscode
```

This will delete the folder with all contents in one go. Sorted.

**Comment by pedes** [comment]
Hi @MizouziE would you mind assigning it to me? Thanks in advance

**Comment by MizouziE** [comment]
All yours @pedes
