### ISSUE TITLE
Chore: Change og:image & og:url meta tags

### ISSUE THREAD

**Issue by MizouziE** [Energy-Price-News-API/energy-prices-api#196]
### What work needs to be performed?

We have new hosting and should therefore make the most of it and point to the always available images we are serving.

In `./src/views/index.html` please change the og:image content to the following:
```
https://energy-price-news.nosweat.cloud/img/energy-prices-api-socials.png
```

In the same file, please change the og:url content to the following:
```
https://energy-price-news.nosweat.cloud/
```

### Additional information

This will make the thumbnail look a bit nicer when a link to this site is shared on social media.

**Comment by aabhas-sao** [comment]
hey @MizouziE, please assign me this issue. I would like to work on it.
