### ISSUE TITLE
[DOC] -  Add contributing.md file

### ISSUE THREAD

**Issue by TAKANOME-DEV** [Energy-Price-News-API/energy-prices-api#29]
### What is incorrect in the documentation?

I would like to add a `contributing.md` file and move the contribution section in the docs there.
We can give more information about how to contribute in this project.

### What should that text say?

We can just put a reference to it like the example below:
```
If you would like to contribute to the project, make sure to check our contributing guidelines first.
```

**Comment by shebuel-oss** [comment]
I can take that up @TAKANOME-DEV

**Comment by MizouziE** [comment]
@TAKANOME-DEV @shebuel-oss This is more or less what I intended on doing in #13  
Granted, I made that issue a month ago so I should have done it by now, but one of the main reasons I began this project was to practice writing things like this. I hope you won't mind if I make a start on this and then ask your input on improving what I start?

**Comment by TAKANOME-DEV** [comment]
Yeah for sure, I didn't pay attention on that issue. Please go ahead 🙏

**Comment by shebuel-oss** [comment]
> @TAKANOME-DEV @shebuel-oss This is more or less what I intended on doing in #13 Granted, I made that issue a month ago so I should have done it by now, but one of the main reasons I began this project was to practice writing things like this. I hope you won't mind if I make a start on this and then ask your input on improving what I start?

Sure, go ahead.

**Comment by MizouziE** [comment]
@shebuel-oss @TAKANOME-DEV Guys, I have a much busier week ahead than expected and although I do really appreciate your understanding when I asked if I could take the lead on this, it would actually be much better if you guys could in fact make this happen.

The project has had some big changes with the most recent pull request, so navigating it has become a little more complex for a beginner, so it is vitally important that a proper `CONTRIBUTING.md` file is created. Check back on #13 for the list of things I originally wanted to ensure were included, but please do trust your own judgement on what else you think is important.

At the end of the day, this project being accessible to beginners and encouraging those first contributions to OSS is more-so the aim. The API and news articles it retrieves are more just a base of the joint exercise.

My apologies for going back on what I said yesterday, but on reflection, I think this would be better.

🙏

**Comment by TAKANOME-DEV** [comment]
Hey @MizouziE don't worry about that, you could make this project private, work on it and sell it.
But you opened it up to beginners like us to contribute, learn and grow together. It's amazing, a BIG THANK YOU👍

**Comment by TAKANOME-DEV** [comment]
Hey @shebuel-oss would you like to take it??

**Comment by shebuel-oss** [comment]
Hey @TAKANOME-DEV Yeah I could take that up. 
No worries @MizouziE, let me work on creating a good CONTRIBUTING.md file for this project. This would help guide new contributors who are beginners to make their first contributions.

**Comment by TAKANOME-DEV** [comment]
Hey @shebuel-oss if you have any question about the contributing file, we are here to help

**Comment by TAKANOME-DEV** [comment]
@shebuel-oss any updates on this ?
