### ISSUE TITLE
Add your favourite news source

### ISSUE THREAD

**Issue by MizouziE** [Energy-Price-News-API/energy-prices-api#49]
### What would you like to share?

As an ice-breaker, I’d like to invite any newcomers to take a look through our list of news sources in `data/sources.json`.

Following the same format, please add a site of your choice by providing the name and a url. Leave the third key value pair as `“base”: “”`. 

We will assess at a later date whether the base needs any attention. 

### Additional information

This issue will remain open as it will be ongoing to try and help as many contributors as possible get involved. 

Thanks for taking a look, and this is a pretty friendly place so ask any questions you think of and someone will be there to help. 

Sam

**Comment by snehashish-ghosh98** [comment]
Hello,
I am a complete beginner and would like to contribute to this issue. Will you assign this to me first or I can just go ahead and create a PR?

**Comment by MizouziE** [comment]
> Hello,
> 
> I am a complete beginner and would like to contribute to this issue. Will you assign this to me first or I can just go ahead and create a PR?

Hi @snehashish-ghosh98 ! This particular issue is a wide open one so just go ahead and create a PR. We're not too strict on whether you reference this issue or not, but use the opportunity to play around with linked PRs and issues etc. 

Very happy to have you on board!

Also thanks for asking a question, we'd really like to encourage others to do the same whenever anything is unclear.

**Comment by MizouziE** [comment]
This can stay open for any newcomers.
