### ISSUE TITLE
[FEAT] - thumbnail image returned improvement

### ISSUE THREAD

**Issue by MizouziE** [Energy-Price-News-API/energy-prices-api#79]
### What feature would you like to see?

As it stands, the image returned with each article object is the `<og:image>` from the parent site.
I think it would be better to have:
- The `<og:image>` from the individual article as some sources have customized ones
- Maybe even different size options using:
    - `<og:image>` as the `"thumb"`
    - Finding a main image as a `"large"`
    - Alt text for the images would also be good to include.

### Possible implementation

If we can do  few different size options and `alt text`, then the images can all go into an array as such:
```js
...
"images": {
    "thumb": {
        "link": "link/to/image/thumb", 
        "alt_text": "This is the alt text"
    },
    "main": {
        "link": "link/to/image/main", 
        "alt_text": "This is the alt text"
    },
...
```

### Additional information

It might be tricky as the sources all have varying ways of displaying images and some do not have any. Be sure to have a fallback like the one currently in use.

Files where these lists are built:
`src/controller/api/newsAPIController.js`
`src/utils/getDataFromCheerio.js`

**Comment by dbsaw** [comment]
## I think those are what you are looking for
![image](https://user-images.githubusercontent.com/66219217/172721402-4303ade8-91fd-4770-9df9-745be8a64b7e.png)

**Comment by MizouziE** [comment]
Yes precisely. The part I couldn't figure out quickly was how to load each individual url in time to then scrape and extract that. 

I did it within the getaDataFromCheerio method's forEach loop and it didn't manage fast enough and wasn't returning something in time. This method is scraping the "parent" and returning data of the children. The image we want is actually data within the child url which isn't part of the $ cheerio loaded html. 

It felt like it needed to be a separate method that takes the url from the article object and appends the image to the article object.

**Comment by KetanParmar07** [comment]
Hello, sir I am interested in solving this issue. so please assign to me this issue.

**Comment by KetanParmar07** [comment]
**Now, What should I do?**

**Comment by MizouziE** [comment]
@KetanParmar07 I'll leave this one open while you're working on the other issue assigned to you. If this is still free when you're done over there then I'll assign it right away.

**Comment by ashwin-acharya01** [comment]
Is it still not resolved? If not then I can work on it.

**Comment by MizouziE** [comment]
Thanks @ashwin-acharya01 

Let me know if you have any questions beyond what is covered in the discussions above

**Comment by ashwin-acharya01** [comment]
Sure

**Comment by MizouziE** [comment]
Hi @ashwin-acharya01 , I hadn't heard from you in a while on this so had a go myself with a solution. Take a look at PR #205 if you'd like to see how it was tackled. The solution used still requires improvements and tests to be written, so if you have anything that could be integrated, it would be appreciated still.
