### ISSUE TITLE
[BUG] Washington post site causing error

### ISSUE THREAD

**Issue by MizouziE** [Energy-Price-News-API/energy-prices-api#88]
### What bug did you encounter?

When running the scraper locally, one of the newer sources triggered a `Error [ERR_FR_TOO_MANY_REDIRECTS]: Maximum number of redirects exceeded`.

Other new sources worked as expected and provided links, but it is unclear if this error blocks subsequent scraping.

Further investigation may be required.

### What did you expect to happen?

No error.

### Screenshots

![image](https://user-images.githubusercontent.com/90829439/175822800-c40fe14c-28cd-4933-a72b-f94b42104010.png)

### Additional information

The error is thrown by `./node_modules/follow-redirects/index.js`

Check the [documentation here for how to change](https://www.npmjs.com/package/follow-redirects) the default `maxRedirects` and see if it can't be made higher to solve this.

**Comment by cortezroberto** [comment]
Hello @MizouziE , I'd like to work on this issue and make some research about the bug!

**Comment by MizouziE** [comment]
Thanks @cortezroberto 🙏 
I'll assign it right away!
